<?php $h=function($value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');};?>
<grid class="admin-expense-editor-layout">
    <form id="admin-expense-details-form" class="admin-form admin-expense-form" style="--cw:8;--cw-sm:12" ajax="true" action="<?=$h($updateAction??'')?>" method="post"><input type="hidden" name="public_id" value="<?=$h($publicId)?>"><input type="hidden" name="supplier[source_public_id]" value="<?=$h($supplier['source_public_id']??'')?>">
        <grid class="fluid">
        <section class="panel admin-panel" style="--cw:12"><div class="panel__header admin-panel__header"><h3><i class="fas fa-receipt"></i> Uitgave</h3></div><grid class="panel__body admin-panel__body admin-form-grid fluid">
            <label class="admin-field admin-field--wide"><span>Titel *</span><input name="title" value="<?=$h($expense->getTitle())?>" required maxlength="255"></label><label class="admin-field"><span>Datum *</span><input type="date" name="expense_date" value="<?=$h($expense->getExpenseDate()->getValue())?>" required></label><label class="admin-field"><span>Categorie *</span><select name="category_public_id" required><?php foreach($categories as$category){if(!$category->isActive()&&$category->getPublicId()!==$expense->getCategoryPublicId()){continue;}$type=$reportingTypes[$category->getReportingType()]??null;?><option value="<?=$h($category->getPublicId())?>"<?=$category->getPublicId()===$expense->getCategoryPublicId()?' selected':''?>><?=$h($category->getName().' · '.($type['label']??$category->getReportingType()).($category->isActive()?'':' (inactief)'))?></option><?php }?></select><small class="admin-field__help">De categorie bepaalt of deze betaling het resultaat en de btw-aftrek beïnvloedt.</small></label><label class="admin-field"><span>Netto *</span><input name="net_amount" value="<?=$h($netAmount)?>" required inputmode="decimal"></label><label class="admin-field"><span>Btw *</span><input name="tax_amount" value="<?=$h($taxAmount)?>" required inputmode="decimal"></label><label class="admin-field"><span>Bruto</span><input value="€ <?=$h($grossAmount)?>" readonly></label><label class="admin-field"><span>Referentie</span><input name="reference" value="<?=$h($expense->getReference())?>" maxlength="128"></label><label class="admin-field admin-field--wide"><span>Omschrijving</span><textarea name="description" rows="4" maxlength="10000"><?=$h($expense->getDescription())?></textarea></label>
        </grid></section>
        <section class="panel admin-panel" style="--cw:12"><div class="panel__header admin-panel__header"><h3><i class="fas fa-building"></i> Leverancier</h3></div><grid class="panel__body admin-panel__body admin-form-grid fluid"><label class="admin-field admin-field--wide"><span>Naam *</span><input name="supplier[name]" value="<?=$h($supplier['name']??'')?>" required maxlength="255"></label><label class="admin-field"><span>Contactpersoon</span><input name="supplier[contact_name]" value="<?=$h($supplier['contact_name']??'')?>" maxlength="128"></label><label class="admin-field"><span>E-mail</span><input type="email" name="supplier[email]" value="<?=$h($supplier['email']??'')?>" maxlength="255"></label><label class="admin-field"><span>KvK-nummer</span><input name="supplier[registration_number]" value="<?=$h($supplier['registration_number']??'')?>" maxlength="128"></label><label class="admin-field"><span>Btw-nummer</span><input name="supplier[tax_number]" value="<?=$h($supplier['tax_number']??'')?>" maxlength="128"></label><label class="admin-field"><span>Landcode *</span><input name="supplier[country_code]" value="<?=$h($supplier['country_code']??'NL')?>" maxlength="2" pattern="[A-Za-z]{2}" required></label></grid></section>
        </grid>
        <div style="--cw:12"><button class="button button-publish" type="submit"><i class="fas fa-save"></i> Opslaan</button></div>
    </form>
    <aside style="--cw:4;--cw-sm:12"><?php include __DIR__.'/CategoryForm.php';?></aside>
    <section class="panel admin-panel admin-expense-attachments" style="--cw:12"><div class="panel__header admin-panel__header"><h3><i class="fas fa-paperclip"></i> Bewijsstukken</h3></div><div class="panel__body admin-panel__body"><?php if($expense->getAttachments()===[]){?><div class="admin-empty-state admin-empty-state--compact"><i class="fas fa-file-arrow-up"></i><p>Nog geen bewijsstukken opgeslagen.</p></div><?php }else{?><ul><?php foreach($expense->getAttachments()as$attachment){?><li><i class="fas fa-file-shield"></i><span><strong><?=$h($attachment->getOriginalName())?></strong><small><?=$h($attachment->getMediaType().' · '.number_format($attachment->getSizeBytes()/1024,1,',','.').' KB')?></small></span><span class="admin-expense-attachment-actions"><a class="button button-secondary" href="<?=$h(rtrim($downloadBaseUrl,'/').'/'.rawurlencode($attachment->getPublicId()))?>"><i class="fas fa-download"></i> Downloaden</a><button class="button button-secondary" type="button" ajax="true" action="<?=$h($removeAttachmentAction)?>" public_id="<?=$h($publicId)?>" attachment_id="<?=$h($attachment->getPublicId())?>" alert="Dit bewijsstuk verwijderen?" use-waiting-icon><i class="fas fa-trash"></i> Verwijderen</button></span></li><?php }?></ul><?php }?>
        <form class="admin-form admin-expense-upload-form" ajax="true" action="<?=$h($uploadAction??'')?>" method="post" enctype="multipart/form-data"><input type="hidden" name="public_id" value="<?=$h($publicId)?>"><label class="admin-field"><span>PDF of afbeelding, maximaal 25 MB</span><input type="file" name="attachment" accept="application/pdf,image/jpeg,image/png,image/webp" required></label><button class="button button-secondary" type="submit"><i class="fas fa-upload"></i> Veilig uploaden</button></form>
    </div></section>
</grid>
