<?php
declare(strict_types=1);
namespace Flexgrid\Modules\AdminExpense\Domain\ValueObject;
final class SupplierSnapshot
{
    private const VERSION=1;private $name,$contactName,$email,$registrationNumber,$taxNumber,$countryCode,$sourcePublicId;
    public function __construct(string $name,string $contactName='',string $email='',string $registrationNumber='',string $taxNumber='',string $countryCode='NL',string $sourcePublicId=''){$name=trim($name);$email=trim($email);$countryCode=strtoupper(trim($countryCode));if(strlen($name)>255){throw new \InvalidArgumentException('Leveranciersnaam mag maximaal 255 tekens bevatten.');}if($name===''&&($contactName!==''||$email!==''||$registrationNumber!==''||$taxNumber!==''||$sourcePublicId!=='')){throw new \InvalidArgumentException('Vul een leveranciersnaam in als je leveranciersgegevens opgeeft.');}if($email!==''&&filter_var($email,FILTER_VALIDATE_EMAIL)===false){throw new \InvalidArgumentException('Leverancier heeft een ongeldig e-mailadres.');}if(preg_match('/^[A-Z]{2}$/D',$countryCode)!==1){throw new \InvalidArgumentException('Leveranciersland moet een ISO-landcode van twee letters zijn.');}foreach([$contactName,$registrationNumber,$taxNumber,$sourcePublicId]as$value){if(strlen(trim($value))>128){throw new \InvalidArgumentException('Leverancierssnapshot bevat een te lange waarde.');}}$this->name=$name;$this->contactName=trim($contactName);$this->email=$email;$this->registrationNumber=trim($registrationNumber);$this->taxNumber=trim($taxNumber);$this->countryCode=$countryCode;$this->sourcePublicId=trim($sourcePublicId);}
    public function toArray():array{return['schema_version'=>self::VERSION,'name'=>$this->name,'contact_name'=>$this->contactName,'email'=>$this->email,'registration_number'=>$this->registrationNumber,'tax_number'=>$this->taxNumber,'country_code'=>$this->countryCode,'source_public_id'=>$this->sourcePublicId];}
    public static function fromArray(array $data):self{if((int)($data['schema_version']??0)!==self::VERSION){throw new \UnexpectedValueException('Onbekende leverancierssnapshotversie.');}return new self((string)($data['name']??''),(string)($data['contact_name']??''),(string)($data['email']??''),(string)($data['registration_number']??''),(string)($data['tax_number']??''),(string)($data['country_code']??''),(string)($data['source_public_id']??''));}
    public function getName():string{return$this->name;}public function getSourcePublicId():string{return$this->sourcePublicId;}
}
