<?php
declare(strict_types=1);
namespace Flexgrid\Modules\AdminExpense\Integration\Banking;
use Flexgrid\Database\Connection;use Flexgrid\Modules\AdminBanking\Application\ReadModel\BankMatchContext;use Flexgrid\Modules\AdminBanking\Application\ReadModel\BankMatchSuggestion;use Flexgrid\Modules\AdminBanking\Contract\BankMatchCandidateProviderInterface;use Flexgrid\Modules\AdminCore\ValueObject\TenantId;
final class MatchCandidateProvider implements BankMatchCandidateProviderInterface
{
    public function suggest(TenantId$tenant,BankMatchContext$context):array
    {
        if($context->getAmountMinor()>=0){return[];}$statement=Connection::getConnections()->prepare("SELECT e.`public_id`,e.`expense_date`,e.`title`,e.`reference`,e.`gross_amount_minor`,COALESCE(JSON_UNQUOTE(JSON_EXTRACT(e.`supplier_snapshot`,'$.name')),'') AS supplier_name FROM `admin_expense` e WHERE e.`tenant_id`=:tenant AND e.`currency`=:currency AND e.`gross_amount_minor`>0 ORDER BY e.`expense_date` DESC LIMIT 200");$statement->execute([':tenant'=>$tenant->toString(),':currency'=>$context->getCurrency()]);$suggestions=[];$wanted=abs($context->getAmountMinor());$haystack=$this->normalize($context->getSearchText());foreach($statement->fetchAll(\PDO::FETCH_ASSOC)as$row){$amount=(int)$row['gross_amount_minor'];$reference=(string)($row['reference']??'');$supplier=(string)$row['supplier_name'];$exact=$amount===$wanted;$referenceMatch=$reference!==''&&strpos($haystack,$this->normalize($reference))!==false;$name=$supplier!==''&&$context->getCounterpartyName()!==''&&$this->containsEither($context->getCounterpartyName(),$supplier);if(!$exact&&!$referenceMatch){continue;}$score=0;$evidence=[];if($exact){$score+=6000;$evidence[]='brutobedrag komt exact overeen';}if($referenceMatch){$score+=2500;$evidence[]='referentie is herkend';}if($name){$score+=1000;$evidence[]='leveranciersnaam komt overeen';}$days=abs((int)((strtotime($context->getBookedOn())-strtotime((string)$row['expense_date']))/86400));if($days<=7){$score+=500;$evidence[]='datum ligt binnen 7 dagen';}elseif($days<=31){$score+=250;$evidence[]='datum ligt binnen 31 dagen';}$score=min(9900,$score);if($score<5000){continue;}$label='Uitgave '.(string)$row['title'].($supplier!==''?' van '.$supplier:'');$suggestions[]=new BankMatchSuggestion('expense',(string)$row['public_id'],$score,$label.': '.implode(', ',$evidence).'.');}return$suggestions;
    }
    private function normalize(string$value):string{return preg_replace('/[^a-z0-9]+/','',strtolower($value));}private function containsEither(string$a,string$b):bool{$a=$this->normalize($a);$b=$this->normalize($b);return$a!==''&&$b!==''&&(strpos($a,$b)!==false||strpos($b,$a)!==false);}
}
