<?php
declare(strict_types=1);
namespace Flexgrid\Modules\AdminExpense\Domain\Model;
use Flexgrid\Modules\AdminCore\ValueObject\Currency;use Flexgrid\Modules\AdminCore\ValueObject\Money;use Flexgrid\Modules\AdminCore\ValueObject\TenantId;use Flexgrid\Modules\AdminExpense\Domain\ValueObject\ExpenseDate;use Flexgrid\Modules\AdminExpense\Domain\ValueObject\SupplierSnapshot;
final class Expense
{
    private $publicId,$tenantId,$categoryPublicId,$currency,$supplier,$date,$title,$description,$reference,$net,$tax,$source,$externalId,$attachments=[];
    public function __construct(string $publicId,TenantId $tenantId,string $categoryPublicId,Currency $currency,SupplierSnapshot $supplier,ExpenseDate $date,string $title,Money $net,Money $tax,string $description='',string $reference='',string $source='',string $externalId=''){$publicId=trim($publicId);$categoryPublicId=trim($categoryPublicId);$title=trim($title);$description=trim($description);$reference=trim($reference);$source=strtolower(trim($source));$externalId=trim($externalId);if($publicId===''||strlen($publicId)>64||$categoryPublicId===''||strlen($categoryPublicId)>64){throw new \InvalidArgumentException('Uitgave vereist geldige publieke ids.');}if($title===''||strlen($title)>255||strlen($description)>10000||strlen($reference)>128){throw new \InvalidArgumentException('Uitgavegegevens overschrijden de maximale lengte.');}if(!$net->getCurrency()->equals($currency)||!$tax->getCurrency()->equals($currency)){throw new \InvalidArgumentException('Uitgavebedragen moeten dezelfde valuta gebruiken.');}if($net->add($tax)->isZero()){throw new \InvalidArgumentException('Een uitgave mag geen bruto nulbedrag hebben.');}if(($source==='')!==($externalId==='')||strlen($source)>64||strlen($externalId)>128){throw new \InvalidArgumentException('Uitgavebron en externe id moeten samen en binnen de limiet worden opgegeven.');}if($source!==''&&preg_match('/^[a-z][a-z0-9_-]{1,63}$/D',$source)!==1){throw new \InvalidArgumentException('Uitgavebron is ongeldig.');}$this->publicId=$publicId;$this->tenantId=$tenantId;$this->categoryPublicId=$categoryPublicId;$this->currency=$currency;$this->supplier=$supplier;$this->date=$date;$this->title=$title;$this->net=$net;$this->tax=$tax;$this->description=$description;$this->reference=$reference;$this->source=$source;$this->externalId=$externalId;}
    public function addAttachment(ExpenseAttachment $attachment):void{foreach($this->attachments as$existing){if($existing->getPublicId()===$attachment->getPublicId()||$existing->getSha256()===$attachment->getSha256()){throw new \DomainException('Uitgavenbijlage-id en inhoud moeten uniek zijn.');}}$this->attachments[]=$attachment;}
    public function getPublicId():string{return$this->publicId;}public function getTenantId():TenantId{return$this->tenantId;}public function getCategoryPublicId():string{return$this->categoryPublicId;}public function getCurrency():Currency{return$this->currency;}public function getSupplierSnapshot():SupplierSnapshot{return$this->supplier;}public function getExpenseDate():ExpenseDate{return$this->date;}public function getTitle():string{return$this->title;}public function getDescription():string{return$this->description;}public function getReference():string{return$this->reference;}public function getNet():Money{return$this->net;}public function getTax():Money{return$this->tax;}public function getGross():Money{return$this->net->add($this->tax);}public function getSource():string{return$this->source;}public function getExternalId():string{return$this->externalId;}public function getAttachments():array{return$this->attachments;}
}
