<?php $h=function($value):string{return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');};?>
<form class="admin-form admin-expense-results" data-admin-expense-filters ajax="true" action="<?=$h($refreshAction??'')?>" method="post">
    <input type="hidden" name="sort" value="<?=$h($query->getSort())?>"><input type="hidden" name="direction" value="<?=$h($query->getDirection())?>"><input type="hidden" name="page" value="<?=$h($result->getPage())?>">
    <div class="admin-summary-grid"><?php foreach($summaryCards as$card){?><article class="admin-stat-card"><span class="admin-tone-icon is-<?=$h($card['tone'])?>"><i class="<?=$h($card['icon'])?>"></i></span><span class="admin-stat-card__content"><span class="admin-stat-card__label"><?=$h($card['label'])?></span><strong class="admin-stat-card__value"><?=$h($card['value'])?></strong><small class="admin-stat-card__meta"><?=$h($card['meta'])?></small></span></article><?php }?></div>
    <div class="admin-help-panel"><i class="fas fa-circle-info"></i><div><strong>Resultaatkosten zijn niet hetzelfde als alle betalingen.</strong><p>Privéopnamen en balansbewegingen staan wel in dit overzicht en in het brutototaal, maar worden niet als kosten in Rapportages meegenomen.</p></div></div>
    <grid class="fluid"><section class="panel admin-panel admin-expense-list-panel" style="--cw:12"><div class="panel__body admin-panel__body admin-panel__body--flush">
        <div class="admin-data-toolbar">
            <label class="admin-data-search"><span class="admin-visually-hidden">Uitgaven zoeken</span><i class="fas fa-search"></i><input type="search" name="q" value="<?=$h($query->getSearch())?>" placeholder="Zoek op titel, leverancier of referentie…" autocomplete="off"></label>
            <select name="category" aria-label="Filter op categorie"><?php foreach($categoryOptions as$value=>$label){?><option value="<?=$h($value)?>"<?=$query->getCategoryPublicId()===$value?' selected':''?>><?=$h($label)?></option><?php }?></select>
            <select name="year" aria-label="Filter op jaar"><option value="">Alle jaren</option><?php foreach($years as$year){?><option value="<?=$h($year)?>"<?=$query->getYear()===$year?' selected':''?>><?=$h($year)?></option><?php }?></select>
            <button class="button button-secondary" type="button" data-admin-expense-reset><i class="fas fa-times"></i> Wissen</button>
        </div>
        <?php echo(new \Flexgrid\Html\Table\TableRenderer($table))->render(); ?>
        <div class="admin-data-pagination"><label><span>Toon</span><select name="per_page" aria-label="Aantal resultaten per pagina"><?php foreach($pageSizes as$pageSize){?><option value="<?=$h($pageSize)?>"<?=$query->getPerPage()===$pageSize?' selected':''?>><?=$h($pageSize)?></option><?php }?></select><span>resultaten</span></label><span class="admin-data-pagination__count"><?=$h($result->getFirstPosition())?>–<?=$h($result->getLastPosition())?> van <?=$h($result->getTotal())?></span><nav class="admin-data-pagination__pages" aria-label="Uitgavenpagina’s"><button type="button" data-admin-expense-page="<?=$h(max(1,$result->getPage()-1))?>"<?=$result->getPage()<=1?' disabled':''?>><i class="fas fa-chevron-left"></i></button><?php foreach($pages as$page){?><button type="button" data-admin-expense-page="<?=$h($page)?>"<?=$page===$result->getPage()?' class="is-active" aria-current="page"':''?>><?=$h($page)?></button><?php }?><button type="button" data-admin-expense-page="<?=$h(min($result->getTotalPages(),$result->getPage()+1))?>"<?=$result->getPage()>=$result->getTotalPages()?' disabled':''?>><i class="fas fa-chevron-right"></i></button></nav></div>
    </div></section></grid>
</form>
